config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :feedbacks
  resources :home
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#home'

  match '/addnews',       to: 'posts#new',            via: 'get'
  match '/allnews',       to: 'posts#index',          via: 'get' 
  match '/allposts',      to: 'posts#admin',          via: 'get' 
  match '/json',          to: 'posts#json',           via: 'get' 
  match '/rss',           to: 'posts#rss',            via: 'get', :defaults => { :format => 'rss' }
  match '/xml',           to: 'posts#customxml',      via: 'get', :defaults => { :format => 'xml' }

  match '/leavefeedback', to: 'feedbacks#new',        via: 'get' 
  match '/allfeedback',   to: 'feedbacks#index',      via: 'get'

  match '/home',          to: 'home#home',            via: 'get'
  match '/cookies',       to: 'home#cookies',         via: 'get'
  match '/rules',         to: 'home#rules',           via: 'get'
  
  match '/signup',        to: 'users#new',            via: 'get'
  match '/allusers',      to: 'users#index',          via: 'get'
  match '/feedlist',      to: 'users#feedlist',       via: 'get'
  match '/myposts',       to: 'users#userposts',      via: 'get'

  match '/signin',        to: 'sessions#new',         via: 'get'
  match '/signout',       to: 'sessions#destroy',     via: 'delete'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name,  presence: true, length: { maximum: 50 }

    validates :email, presence: true, 
    				  format: { with: VALID_EMAIL_REGEX }, 
    				  uniqueness: { case_sensitive: false }
    				  
    validates :password, length: { minimum: 6 }

    has_secure_password

    def User.new_remember_token
   	 	SecureRandom.urlsafe_base64
  	end

 	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
  	end

  	private

    def create_remember_token
      	self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  def show
    @user = User.find(params[:id]) or not_found
  end

  def new
  	@user = User.new
  end

  def index
    @user = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      @error = "Oops, something wrong!"
      render 'edit'
    end
  end

  def feedlist
    @feed = Feedback.where(author: current_user.name)
  end

  def userposts
    @post = Post.where(author: current_user.name)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to :back
  end

private
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url
    end
  end

  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "/layouts/header" %>

<div class="row">
  <div class="col s8 offset-s2">
    <div class="card-panel">
          <h1>Hello, @user!</h1>
          <h5>There is place for editing your profile</h5>

          <%= form_for(@user) do |f| %>
            <%= render 'layouts/errors_user_create' %>
            <p>
              <%= f.text_field :name, placeholder: "Your name" %>
            </p>
            <p>
              <%= f.text_field :email, placeholder: "email" %>
            </p>
            <p>
              <%= f.password_field :password, placeholder: "Password" %>
            </p>
            <p>
              <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
            </p>
            <%= f.submit "Update my account", class: "btn btn-large purple lighten-2" %>
          <% end %>  
    </div>
  </div>
</div>

app/views/users/feedlist.html.erb
<%= render "layouts/header" %>

<div class="row">
	<div class="col s10 offset-s1">
		<table id="feedback_user">
		    <thead>
		          <tr>

		              <th data-field="message">Message</th>
		              <th data-field="time">Submited</th>
			          <th data-field="vieewed">Viewed</th>
			          <th data-field="answer">Answer</th>
	    			  <th data-field="delete">Delete</th>		
		          </tr>
		    </thead>

		    <tbody>
		    	<% @feed.each do |message| %>
		          <tr>
		            <td><%= message.text %></td>
		            <td><%= time_ago_in_words(message.created_at) %></td>

		            <% if message.adminview? %>
		            	<td>Yes, <%= time_ago_in_words(message.updated_at)%> ago</td>
						<td><%= message.adminanswer %></td>
		            <% else %>
		            	<td>Not yet</td>
		            	<td>Has no answer!</td>
		            <% end %>
    				<td><%= link_to "delete", message, method: :delete, data: { confirm: "You sure?" } %></td>
		          </tr>
		        <% end %>
		    <tbody>
		</table>
	</div>
</div>

app/views/users/index.html.erb
<%= render 'layouts/header' %>
<div class="row">
	<div class="col s10 m12 offset-s1">
		<table id="users">
		    <thead>
		          <tr>
		              <th data-field="author">Name</th>
		              <th data-field="email">email</th>
		              <th data-field="registred">Registred</th>
		              <% if current_user.admin? %>
    				  <th data-field="delete">Kill @user</th>
 					  <% end %>
		          </tr>
		    </thead>

		    <tbody>
		    	<% @user.each do |current| %>
		          <tr>
		            <td><%= link_to current.name, current %></td>
		            <td><%= current.email %></td>
		            <td><%= time_ago_in_words(current.created_at) %></td>
		            <% if current_user.admin? %>
    					<td><%= link_to "delete", current, method: :delete, data: { confirm: "You sure?" } %></td>
 					<% end %>
		          </tr>
		        <% end %>
		    <tbody>
		</table>
	</div>
</div>

app/views/users/new.html.erb
<%= render "/layouts/header" %>

<div class="row">
  <div class="col s8 offset-s2">
    <div class="card-panel">
          <h1>Hello, @user!</h1>
          <h5>After registration you'll have access to new places</h5>

          <%= form_for(@user) do |f| %>
            <%= render 'layouts/errors_user_create' %>
            <p>
              <%= f.text_field :name, placeholder: "Your name" %>
            </p>
            <p>
              <%= f.text_field :email, placeholder: "email" %>
            </p>
            <p>
              <%= f.password_field :password, placeholder: "Password" %>
            </p>
            <p>
              <%= f.password_field :password_confirmation, placeholder: "Confirm password" %>
            </p>
            <%= f.submit "Create my account", class: "btn btn-large purple lighten-2" %>
          <% end %>  
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "layouts/header" %>

<div class="row">
	<div class="col s6 offset-s3">
		<div class="userbox">
			<p>
				<%= image_tag "user/user.png", class: "responsive-img circle", size: "500x500"  %>
			</p>
			<p>
			<div class="card-panel">
					<span class="userdescription">
						<% if current_user.admin? %>
		    				<h2>Hi, @admin!</h2>
		    				@allfeedback: <%= link_to 'feed', allfeedback_path %></br>
		    				@allposts: <%= link_to 'posts', allposts_path %></br>
		    			<% else %>
		    				<h2>Hi, @user!</h2>
		    				@feedback: <%= link_to 'feed',  feedlist_path %></br>
		    				@posts: <%= link_to 'posts',  myposts_path %></br>
		 				<% end %>
						@user:  <%= @user.name %>, </br>
						@email: <%= @user.email %>
					</span>
				</p>
				<p>
					<%= button_to "Settings", edit_user_path(current_user), :class => "btn btn-large purple lighten-2", :method => :get  %>
		      	</p>
	      	</div>
		</div>
	</div>
</div>

app/views/users/userposts.html.erb
<%= render 'layouts/header' %>

<div class="row">
	<div class="col s10 offset-s1">
	<h3>My own posts</h3>
		<table id="userposts">
		    <thead>
		          <tr>
		              <th data-field="title">Title</th>
	    			  <th data-field="edit">Edit</th>
	    			  <th data-field="delete">Delete</th>		
		          </tr>
		    </thead>
		    <tbody>
		    	<% @post.each do |message| %>
	          	<tr>
		            <td><%= message.title %></td>
		            <td><%= link_to "Edit", edit_post_path(message) %></td>
    				<td><%= link_to "Delete", message, method: :delete, data: { confirm: "You sure?" } %></td>
		        </tr>
	        <% end %>
		    <tbody>
		</table>
	</div>
</div>