config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :feedbacks
  resources :home
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#home'

  match '/addnews',       to: 'posts#new',            via: 'get'
  match '/allnews',       to: 'posts#index',          via: 'get' 
  match '/allposts',      to: 'posts#admin',          via: 'get' 
  match '/json',          to: 'posts#json',           via: 'get' 
  match '/rss',           to: 'posts#rss',            via: 'get', :defaults => { :format => 'rss' }
  match '/xml',           to: 'posts#customxml',      via: 'get', :defaults => { :format => 'xml' }

  match '/leavefeedback', to: 'feedbacks#new',        via: 'get' 
  match '/allfeedback',   to: 'feedbacks#index',      via: 'get'

  match '/home',          to: 'home#home',            via: 'get'
  match '/cookies',       to: 'home#cookies',         via: 'get'
  match '/rules',         to: 'home#rules',           via: 'get'
  
  match '/signup',        to: 'users#new',            via: 'get'
  match '/allusers',      to: 'users#index',          via: 'get'
  match '/feedlist',      to: 'users#feedlist',       via: 'get'
  match '/myposts',       to: 'users#userposts',      via: 'get'

  match '/signin',        to: 'sessions#new',         via: 'get'
  match '/signout',       to: 'sessions#destroy',     via: 'delete'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
		@news   = Feedjira::Feed.fetch_and_parse('http://k.img.com.ua/rss/ua/all_news2.0.xml').entries[0,5]
		@sience = Feedjira::Feed.fetch_and_parse('http://news.sciencemag.org/rss/current.xml').entries[0,5]
	end
end
#http://www.gametrailers.com/shows/feed

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/cookies.html.erb
<%= render 'layouts/header' %>

<div class="section white">
    <div class="row container">
      <h2 class="header">Cookies</h2>
      <p class="grey-text text-darken-3 lighten-3">My dear friend! Be happy and free! Thee are no cookies used by this site. But in common future situation will be changed.</p>
      <%= image_tag "cookies.jpg", class: "responsive-img"%>
    </div>
</div>

app/views/home/home.html.erb
<%= render 'layouts/header' %>
<div class="row">
  <div class="col s6">
    <% @news.each do |item| %>
      <ul class="collection">
       <li class="collection-item avatar">
          <%= image_tag item.image, class: "circle", width: "60px" %>
          <span class="title">From: <em>Korrespondent.net</em></span>
          <p>
            <%= link_to item.title, item.url %>
          </p>
        </li>
      </ul>
    <% end %>
  </div>
  <div class="col s6">
    <% @sience.each do |item| %>
      <ul class="collection">
       <li class="collection-item avatar">
          <%= image_tag item.image, class: "circle", width: "60px" %>
          <span class="title">From: <em>Sciencemag.org</em></span>
          <p>
            <%= link_to item.title, item.url %>
          </p>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/home/rules.html.erb
<%= render 'layouts/header' %>

      <div class="row">
        <div class="col s8 offset-s2">
          <div class="card">
            <div class="card-content">
            <p>
				<h3>Rules, Regulations, and Disclaimers</h3>

				<h4>For using this Website</h5>

				<p>American Express Company, its subsidiaries and affiliates ("American Express") requires that all the visitors to our site(s) on the World Wide Web (the "Site") adhere to the following rules and regulations. By accessing the Site you indicate your acknowledgment and acceptance of these terms and conditions.</p>

				<ul>
				    <li> 
				    	<h4>LAWS AND REGULATIONS</h4>
				    		<p>User access to and use of the Site is subject to all applicable international, federal, state, and local laws and regulations.</p>
				    </li>

				    <li> 
				    	<h4>COPYRIGHT/TRADEMARKS</h4>
				    		<p>The trademarks, logos, and service marks ("Marks") displayed on the Site are the property of American Express and other parties. Users are prohibited from using any Marks for any purpose including, but not limited to, use as metatags on other pages or sites on the World Wide Web without the written permission of American Express or such third party which may own the Marks. All information and content including any software programs available on or through the Site ("Content") is protected by copyright. Users are prohibited from modifying, copying, distributing, transmitting, displaying, publishing, selling, licensing, creating derivative works, or using any Content available on or through the Site for commercial or public purposes.</p>
				    </li>

				    <li> 
				    	<h4>HYPERLINKING</h4>
				    		<p>THIS SITE MAY PROVIDE A LINK TO OTHER SITES BY ALLOWING THE USER TO LEAVE THIS SITE TO ACCESS THIRD-PARTY MATERIAL OR BY BRINGING THE THIRD-PARTY MATERIAL INTO THIS SITE VIA "INVERSE" HYPERLINKS AND FRAMING TECHNOLOGY (A "LINKED SITE"). AMERICAN EXPRESS HAS NO DISCRETION TO ALTER, UPDATE, OR CONTROL THE CONTENT ON A LINKED SITE. THE FACT THAT AMERICAN EXPRESS HAS PROVIDED A LINK TO A SITE IS NOT AN ENDORSEMENT, AUTHORIZATION, SPONSORSHIP, OR AFFILIATION WITH RESPECT TO SUCH SITE, ITS OWNERS, OR ITS PROVIDERS. THERE ARE INHERENT RISKS IN RELYING UPON USING OR RETRIEVING ANY INFORMATION FOUND ON THE INTERNET, AND AMERICAN EXPRESS URGES YOU TO MAKE SURE YOU UNDERSTAND THESE RISKS BEFORE RELYING UPON, USING, OR RETRIEVING ANY SUCH INFORMATION ON A LINKED SITE.</p>
				    </li>

				    <li> 
				    	<h4>NO WARRANTIES</h4>
				    		<p>ALL CONTENT, PRODUCTS, AND SERVICES ON THE SITE OR OBTAINED FROM A WEBSITE TO WHICH THE SITE IS LINKED (A "LINKED SITE") ARE PROVIDED TO YOU "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, SECURITY, OR ACCURACY.</p>
				    </li>	        
				</ul>
			</p>
            </div>
            <div class="card-action">
              <%= link_to "About cookies", cookies_path %>
            </div>
          </div>
        </div>
      </div>