config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :feedbacks
  resources :home
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#home'

  match '/addnews',       to: 'posts#new',            via: 'get'
  match '/allnews',       to: 'posts#index',          via: 'get' 
  match '/allposts',      to: 'posts#admin',          via: 'get' 
  match '/json',          to: 'posts#json',           via: 'get' 
  match '/rss',           to: 'posts#rss',            via: 'get', :defaults => { :format => 'rss' }
  match '/xml',           to: 'posts#customxml',      via: 'get', :defaults => { :format => 'xml' }

  match '/leavefeedback', to: 'feedbacks#new',        via: 'get' 
  match '/allfeedback',   to: 'feedbacks#index',      via: 'get'

  match '/home',          to: 'home#home',            via: 'get'
  match '/cookies',       to: 'home#cookies',         via: 'get'
  match '/rules',         to: 'home#rules',           via: 'get'
  
  match '/signup',        to: 'users#new',            via: 'get'
  match '/allusers',      to: 'users#index',          via: 'get'
  match '/feedlist',      to: 'users#feedlist',       via: 'get'
  match '/myposts',       to: 'users#userposts',      via: 'get'

  match '/signin',        to: 'sessions#new',         via: 'get'
  match '/signout',       to: 'sessions#destroy',     via: 'delete'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/models/post.rb
class Post < ActiveRecord::Base
	default_scope -> { order('created_at DESC') }
	
	validates :image,  		presence: true
	validates :title, 		presence: true
	validates :text,   		presence: true, length: { minimum: 6 }
	validates :author, 		presence: true
	validates :security, 	presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	require 'nokogiri'

	def not_found
		raise ActionController::RoutingError.new('Not Found')
	end

	def new
		@post = Post.new()
	end

	def customxml
		@posts = Post.where(:visibility => true, :security => 1)
	end

	def show
		@post = Post.find_by_id(params[:id]) or not_found

		respond_to do |format|
			format.html
			format.xml  {render :xml => @post}
			format.json {render json: @post.as_json()}
			format.js
		end
	end

	def create
		@post = Post.new(params_req)
		if signed_in?
			@post.author = current_user.name
		end

		if @post.save
			redirect_to @post
		else
			render "new"
		end
	end

	def edit
    	@post = Post.find(params[:id])
  	end

  	def admin
    	@post = Post.all
  	end

    def update
    	@post = Post.find(params[:id])
    	if @post.update_attributes(params_req)
      		redirect_to allposts_path
    	else
     		@error = "Oops, something wrong!"
      		render 'edit'
   		end
  	end

	def index
		@post = Post.paginate(:page => params[:page], :per_page => 5)
		@post_xml = Post.where(:visibility => true, :security => 1)

		respond_to do |format|
			format.html
			format.xml {render :xml => @post_xml}
		end
	end

	def rss
		@post = Post.where(:visibility => true, :security => 1)		# Visible posts + for all
		respond_to do |format|
		   format.rss { render :layout => false }
		end
	end

	def json
		@post = Post.where(:visibility => true, :security => 1)		# Visible posts + for all
		render json: @post
	end

	def destroy
    	Post.find(params[:id]).destroy
   		redirect_to :back
  	end

	private

	def params_req
		 params.require(:post).permit(:title, :text, :author, :image, :security, :visibility)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/admin.html.erb
<%= render "layouts/header" %>

<% if signed_in? %>
	<div class="row">
		<div class="col s10 offset-s1">
			<table id="posts">
			    <thead>
			          <tr>
			              <th data-field="author">Author</th>
			              <th data-field="title">Title</th>
			              <th data-field="created">Added</th>

			        <% if current_user.admin? %>
				            <th data-field="visibility">Visibility</th>
		    				    <th data-field="security">Security</th>
										<th data-field="save"> Commit</th>
		    				    <th data-field="edit">Edit</th>
		    				    <th data-field="delete">Delete</th>
	 					  <% end %>

			          </tr>
			    </thead>

			    <tbody>
			    	<% @post.each do |message| %>
			          <tr>

			            <td><%= message.author %></td>
			            <td><%= message.title %></td>
			            <td><%= time_ago_in_words(message.created_at)%> ago</td>

			            <% if current_user.admin? %>
			         		<%= form_for(message, remote: true) do |f| %>
				            	<td>
						                <%= f.select :visibility, [
						                                          ["Show", true],
						                                          ["Hide", false]
						                                          ], {}, {class: "browser-default"} %>
										  </td>

			            		<td>
					                    <%= f.select :security, [
						                                          ["All", 1],
						                                          ["Users", 2]
						                                          ], {}, {class: "browser-default"} %>
			            		</td>

											<td>
												<%= f.submit "Save" %>
											</td>
			            	<% end %>

			            	<td><%= link_to "Edit", edit_post_path(message) %></td>
	    					<td><%= link_to "Delete", message, method: :delete, data: { confirm: "You sure?" } %></td>

	 					<% end %>
			          </tr>
			        <% end %>
			    <tbody>
			</table>
		</div>
	</div>
<% else %>
	<p>
		<h3>You not authorised to be there!</h3>
		<h4>Login first to see feedback!</h4>
	</p>
<% end %>

app/views/posts/edit.html.erb
<%= render "layouts/header" %>

<% if signed_in? %>
  <% if current_user.admin? or current_user.name == @post.author %>
  <div class="row">
    <div class="col s8 offset-s2">
      <div class="card">
        <div class="card-image">
              <%= image_tag "paper/edit.jpg", class: "img-responsive"%>
              <span class="card-title white-text">Editing post</span>       
        </div>
              <div class="card-content">
              
          <%= form_for(@post) do |f| %>
                  <p>      <%= render 'layouts/errors_add_news' %>     </p>
                  <p><%= f.text_field :title,     class: "form-control", placeholder: "Title"%>                    </p>   
                  <p><%= f.text_field :image,     class: "form-control", placeholder: "Image URL"%>                </p> 
                  <p><%= f.text_area  :text,      class: "form-control", placeholder: "Text"%>                     </p> 

                  <% if current_user.admin? %>
                    <p>
                      Security level: 
                      <%= f.select :security, [
                                            ["All", 1], 
                                            ["Users and admin", 2]
                                            ], {}, {class: "browser-default"} %>
                    </p>   
                      Visibility: 
                      <%= f.select :visibility, [
                                            ["Show", true], 
                                            ["Hide", false]
                                            ], {}, {class: "browser-default"} %>
                    </p>   
                  <% end %>
              </div>
          <div class="card-action">
                <%= f.submit "Update Post", class: "btn btn-large purple lighten-2" %>
              </div>
          <% end %>       
      </div>
    </div>
  </div>
  <% else %>
      <h2>You aren't an author of this article!</h2>
  <% end %>
<% else %>
  <h2>You have no preveligious to edit this post!</h2>
<% end %>

app/views/posts/index.html.erb
<% provide(:title, "All news") %>
<%= render 'layouts/header' %>

<div class="row">
  <div class="col s6 offset-s3">
    <% @post.each do |record| %>
      <% if current_user != nil && current_user.admin? %>
        <% admin = true %>
          <% else %>
        <% admin = false %>
      <% end %>

      <% if record.visibility? || admin %>
        <!-- Is there visibibility? -->
        <% if record.security == 2 && !signed_in? %>
            <!-- If I'am not signed user for locked post-->
            <div class="card">
              <div class="card-content">
                <p><h5>This post is only for users!</h5></p>
              </div>
              <div class="card-action">
                <%= link_to "Sign up now!", signup_path %>
              </div>
            </div>
        <% else %>     <!-- If I'am signed user or it's unlocked-->
          <div class="card">
            <div class="card-image">
              <%= image_tag record.image,  class: "responsive-img" %>
                <span class="card-title"><%= link_to record.title, record%></span>
            </div>
            <div class="card-content">
              <em>Author:<%= record.author %></em>
            </div>
            <div class="card-action">
              <%= link_to "More information", record %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <%= will_paginate @post %>
</div>

app/views/posts/new.html.erb
<%= render 'layouts/header' %>

<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
      <div class="card-image">
            <%= image_tag("paper/1.jpg")%>
            <span class="card-title grey-text text-darken-4">Adding some news</span>       
      </div>
            <div class="card-content">
            
        <%= form_for(@post) do |f| %>
                <p>      <%= render 'layouts/errors_add_news' %>     </p>
                <p><%= f.text_field :title,     class: "form-control", placeholder: "Title"%>                    </p>   
                <p><%= f.text_field :author,    class: "form-control", placeholder: "Author"%>                   </p>  
                <p><%= f.text_field :image,     class: "form-control", placeholder: "Image URL"%>                </p> 
                <p><%= f.text_area  :text,      class: "form-control", placeholder: "Text"%>                     </p>    
            </div>
        <div class="card-action">
              <%= f.submit "Add Post", class: "btn btn-large purple lighten-2" %>
            </div>
        <% end %>       
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'layouts/header' %>
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card">
    <div class="card-image">
      <%= image_tag @post.image, class: "responsive-img"%>
      <span class="card-title"><%= @post.title %></span>
    </div>
   <div class="card-content">
     <p>
       <small>
         <em>Author: <%= @post.author %></em>
       </small>
     </p>
     <p><%= @post.text %></p>
  </div>
</div>