config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :feedbacks
  resources :home
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#home'

  match '/addnews',       to: 'posts#new',            via: 'get'
  match '/allnews',       to: 'posts#index',          via: 'get' 
  match '/allposts',      to: 'posts#admin',          via: 'get' 
  match '/json',          to: 'posts#json',           via: 'get' 
  match '/rss',           to: 'posts#rss',            via: 'get', :defaults => { :format => 'rss' }
  match '/xml',           to: 'posts#customxml',      via: 'get', :defaults => { :format => 'xml' }

  match '/leavefeedback', to: 'feedbacks#new',        via: 'get' 
  match '/allfeedback',   to: 'feedbacks#index',      via: 'get'

  match '/home',          to: 'home#home',            via: 'get'
  match '/cookies',       to: 'home#cookies',         via: 'get'
  match '/rules',         to: 'home#rules',           via: 'get'
  
  match '/signup',        to: 'users#new',            via: 'get'
  match '/allusers',      to: 'users#index',          via: 'get'
  match '/feedlist',      to: 'users#feedlist',       via: 'get'
  match '/myposts',       to: 'users#userposts',      via: 'get'

  match '/signin',        to: 'sessions#new',         via: 'get'
  match '/signout',       to: 'sessions#destroy',     via: 'delete'

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

end

app/views/layouts/_errors_add_feedback.html.erb
<% if @feedback.errors.any? %>
    <div id="error_explanation">
    	<div class="alert alert-error">
      The form contains <%= pluralize(@feedback.errors.count, "error") %>.
      <ul>
          <% @feedback.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
      <% end %>
    </ul>
    </div>
<% end %>

app/views/layouts/_errors_add_news.html.erb
<% if @post.errors.any? %>
    <div class="alert alert-danger" role="alert">
      The form contains <%= pluralize(@post.errors.count, "error") %>.
      <ul>
          <% @post.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
      <% end %>
    </ul>
    </div>
<% end %>

app/views/layouts/_errors_user_create.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <h4>The form contains <%= pluralize(@user.errors.count, "error") %>.</h4>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!--
<footer class="page-footer purple darken-1 fixed-bottom">
  	<div class="container">
        <div class="row">
            <div class="col l6 s12">
             <h5 class="white-text">Newstler</h5>
                <p class="grey-text text-lighten-4">The Freshest news form famous sites!.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">News parsed from:</h5>
                <ul>
                  <%= link_to "Korrespondent.net", "korrespondent.com", class: "grey-text text-lighten-3" %></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2015 Roman Kaporin
            <%= link_to "About", "https://github.com/ic2hrmk/weblab", class: "grey-text text-lighten-4 right" %>
        </div>
    </div>
    </div>
</footer>
-->

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <a class="btn-floating btn-large purple lighten-2" href="/leavefeedback">
    <i class="large material-icons">mode_edit</i>
   </a>
</div>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper purple darken-1">
    <a class="brand-logo" href="#!">
    	<%= link_to image_tag("nw.png", size: "64x64"), root_path %>
    </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
       <li><%= link_to "Add Article", addnews_path %></li>
       <li><%= link_to "News", allnews_path %> </li>
       <li><%= link_to "Rules", rules_path %> </li>
<% if signed_in? %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li class="active">
            <%= link_to "Sign out", signout_path, method: "delete" %>
        </li>
<% else %>
        <li class="active">
            <%= link_to "Sign in", signin_path %>
        </li>
<% end %>

      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <%= yield %>
  <%= render 'layouts/footer' %>


</body>
</html>